# Generated by Django 3.1.2 on 2020-10-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
