# Generated by Django 3.1.2 on 2020-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_bug_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
